name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Example-Actions-Job:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that trigered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      # Runner information
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
